services:
  - type: web
    name: student-exam-fe
    runtime: static
    buildCommand: pnpm install --frozen-lockfile && pnpm build
    staticPublishPath: dist/student-exam-fe/browser
    pullRequestPreviewsEnabled: false
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    headers:
      - path: /*
        name: X-Frame-Options
        value: DENY
